-- Initial local learning-engine schema. This migration creates structure only:
-- it intentionally inserts no topics, levels, or questions.
CREATE TABLE "LearnerProfile" ("id" TEXT NOT NULL PRIMARY KEY, "displayName" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Topic" ("id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT);
CREATE UNIQUE INDEX "Topic_slug_key" ON "Topic"("slug");
CREATE TABLE "Level" ("id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX "Level_slug_key" ON "Level"("slug");
CREATE TABLE "LevelTopic" ("levelId" TEXT NOT NULL, "topicId" TEXT NOT NULL, PRIMARY KEY ("levelId", "topicId"), CONSTRAINT "LevelTopic_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LevelTopic_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "Topic" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Question" ("id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "prompt" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "QuizQuestion" ("questionId" TEXT NOT NULL PRIMARY KEY, CONSTRAINT "QuizQuestion_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "QuizChoice" ("id" TEXT NOT NULL PRIMARY KEY, "quizQuestionId" TEXT NOT NULL, "label" TEXT NOT NULL, "isCorrect" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL, CONSTRAINT "QuizChoice_quizQuestionId_fkey" FOREIGN KEY ("quizQuestionId") REFERENCES "QuizQuestion" ("questionId") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "QuizChoice_quizQuestionId_sortOrder_key" ON "QuizChoice"("quizQuestionId", "sortOrder");
CREATE TABLE "FlashcardQuestion" ("questionId" TEXT NOT NULL PRIMARY KEY, "front" TEXT NOT NULL, "back" TEXT NOT NULL, CONSTRAINT "FlashcardQuestion_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "MindMapQuestion" ("questionId" TEXT NOT NULL PRIMARY KEY, "layoutMetadata" TEXT, CONSTRAINT "MindMapQuestion_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "MindMapNode" ("id" TEXT NOT NULL PRIMARY KEY, "mindMapQuestionId" TEXT NOT NULL, "parentNodeId" TEXT, "label" TEXT, "isTarget" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL, CONSTRAINT "MindMapNode_mindMapQuestionId_fkey" FOREIGN KEY ("mindMapQuestionId") REFERENCES "MindMapQuestion" ("questionId") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "MindMapNode_mindMapQuestionId_sortOrder_key" ON "MindMapNode"("mindMapQuestionId", "sortOrder");
CREATE TABLE "MindMapChoice" ("id" TEXT NOT NULL PRIMARY KEY, "mindMapQuestionId" TEXT NOT NULL, "label" TEXT NOT NULL, "isCorrect" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL, CONSTRAINT "MindMapChoice_mindMapQuestionId_fkey" FOREIGN KEY ("mindMapQuestionId") REFERENCES "MindMapQuestion" ("questionId") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "MindMapChoice_mindMapQuestionId_sortOrder_key" ON "MindMapChoice"("mindMapQuestionId", "sortOrder");
CREATE TABLE "LevelQuestion" ("levelId" TEXT NOT NULL, "questionId" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL, PRIMARY KEY ("levelId", "questionId"), CONSTRAINT "LevelQuestion_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LevelQuestion_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "LevelQuestion_levelId_sortOrder_key" ON "LevelQuestion"("levelId", "sortOrder");
CREATE TABLE "LevelAttempt" ("id" TEXT NOT NULL PRIMARY KEY, "learnerProfileId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'IN_PROGRESS', "questionOrder" TEXT NOT NULL, "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, CONSTRAINT "LevelAttempt_learnerProfileId_fkey" FOREIGN KEY ("learnerProfileId") REFERENCES "LearnerProfile" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LevelAttempt_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "QuestionAttempt" ("id" TEXT NOT NULL PRIMARY KEY, "levelAttemptId" TEXT NOT NULL, "questionId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'UNANSWERED', "finalStatus" TEXT NOT NULL DEFAULT 'IN_PROGRESS', "errorCount" INTEGER NOT NULL DEFAULT 0, "eventuallyCorrect" BOOLEAN NOT NULL DEFAULT false, "sequencePosition" INTEGER NOT NULL, "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "firstAnsweredAt" DATETIME, "completedAt" DATETIME, CONSTRAINT "QuestionAttempt_levelAttemptId_fkey" FOREIGN KEY ("levelAttemptId") REFERENCES "LevelAttempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "QuestionAttempt_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "QuestionAttempt_levelAttemptId_questionId_key" ON "QuestionAttempt"("levelAttemptId", "questionId");
CREATE UNIQUE INDEX "QuestionAttempt_levelAttemptId_sequencePosition_key" ON "QuestionAttempt"("levelAttemptId", "sequencePosition");
CREATE TABLE "AnswerSelection" ("id" TEXT NOT NULL PRIMARY KEY, "questionAttemptId" TEXT NOT NULL, "answerId" TEXT NOT NULL, "label" TEXT, "isCorrect" BOOLEAN NOT NULL, "selectedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnswerSelection_questionAttemptId_fkey" FOREIGN KEY ("questionAttemptId") REFERENCES "QuestionAttempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "AnswerSelection_questionAttemptId_answerId_key" ON "AnswerSelection"("questionAttemptId", "answerId");
CREATE TABLE "LearnerProgress" ("learnerProfileId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "bestStatus" TEXT NOT NULL DEFAULT 'IN_PROGRESS', "bestPercentage" INTEGER NOT NULL DEFAULT 0, "lastAttemptedAt" DATETIME, PRIMARY KEY ("learnerProfileId", "levelId"), CONSTRAINT "LearnerProgress_learnerProfileId_fkey" FOREIGN KEY ("learnerProfileId") REFERENCES "LearnerProfile" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LearnerProgress_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
