export type GlossaryEntry = Readonly<{
  term: string;
  definition: string;
}>;

export const glossaryEntries: GlossaryEntry[] = [
  { term: "AC/DC", definition: "Agent-Centric Development Cycle, Sonar's framing for guiding AI coding agents, verifying their output, and helping solve issues." },
  { term: "Adoption", definition: "Meaningful, repeated use of Sonar in daily engineering workflows, such as IDE feedback, pull-request analysis, and quality gates." },
  { term: "Advanced SAST", definition: "Security analysis that extends standard SAST with deeper data-flow reasoning, including flows that involve third-party library boundaries." },
  { term: "Advanced Security", definition: "SonarQube capability set for deeper application security and dependency risk use cases, including SCA and supply-chain visibility." },
  { term: "AI Code Assurance", definition: "SonarQube governance for projects that contain AI-generated code, usually involving dedicated quality gates and stronger verification expectations." },
  { term: "AI CodeFix", definition: "Sonar capability that suggests fixes for selected issues so developers can remediate findings faster while still reviewing the change." },
  { term: "AI-generated code", definition: "Code produced partly or fully by an AI coding assistant or agent. It still needs independent verification for bugs, vulnerabilities, and maintainability." },
  { term: "Application Security", definition: "Practices and tooling that reduce security risk in application code, dependencies, configuration, and delivery workflows." },
  { term: "Branch analysis", definition: "Analysis of a non-main branch so teams can understand quality and security before changes are merged or released." },
  { term: "Bug", definition: "A reliability issue that may cause incorrect behavior at runtime. In Sonar vocabulary, bugs are distinct from code smells and vulnerabilities." },
  { term: "CI/CD", definition: "Continuous Integration and Continuous Delivery or Deployment: automated workflows for building, testing, scanning, and releasing software." },
  { term: "Clean as You Code", definition: "Sonar's improvement model that focuses strict standards on new code so teams stop adding problems while gradually improving older code." },
  { term: "Code coverage", definition: "A measure of how much code is exercised by tests. Coverage is useful for quality gates, but high coverage does not prove code is bug-free." },
  { term: "Code smell", definition: "A maintainability issue that makes code harder to understand, test, or change, without necessarily being a bug or vulnerability." },
  { term: "Cognitive complexity", definition: "A measure of how difficult code is to understand, especially due to nested control flow and branching logic." },
  { term: "Community Build", definition: "The free, open-source self-managed SonarQube option for core code quality workflows." },
  { term: "Compliance", definition: "The ability to demonstrate that software practices follow required standards, policies, or regulations using repeatable evidence." },
  { term: "Connected Mode", definition: "A SonarQube for IDE setup that connects the IDE to SonarQube Cloud or SonarQube Server so local feedback matches project rules and settings." },
  { term: "Context Augmentation", definition: "Supplying AI agents with project-aware standards, architecture, and quality context so generated code better fits the codebase." },
  { term: "CSE", definition: "Customer Success Engineer: a technical advisor focused on customer adoption, maturity, health, value realization, and successful Sonar usage." },
  { term: "Customer health", definition: "A view of account status based on adoption, risk signals, stakeholder engagement, maturity, and value realization." },
  { term: "Dashboard", definition: "A SonarQube view that summarizes project, portfolio, or organization quality and security status." },
  { term: "Dependency", definition: "A third-party library or package used by an application. Dependency risk is usually handled through SCA." },
  { term: "Developer workflow", definition: "The normal path developers follow to write, review, merge, and ship code, including IDE, pull request, and CI/CD steps." },
  { term: "DevOps platform", definition: "A system such as GitHub, GitLab, Bitbucket, or Azure DevOps that hosts repositories and pull-request workflows." },
  { term: "Duplication", definition: "Repeated code that can increase maintenance cost because fixes may need to be made consistently in multiple places." },
  { term: "False positive", definition: "A finding that appears to violate a rule but is judged not to be a real issue in the specific context." },
  { term: "Gate failure", definition: "A result where one or more quality gate conditions are not met, often causing a pull request or pipeline to be blocked." },
  { term: "Governance", definition: "The policies, standards, permissions, reports, and quality gates that help teams apply consistent engineering rules at scale." },
  { term: "Hotspot review", definition: "The human review process for a Security Hotspot to decide whether security-sensitive code is safe or must be fixed." },
  { term: "IaC scanning", definition: "Infrastructure as Code scanning: analysis of configuration files such as Terraform, Kubernetes, or cloud templates for security and reliability risks." },
  { term: "IDE", definition: "Integrated Development Environment, the editor or development tool where developers write code." },
  { term: "Issue", definition: "A Sonar finding created when analyzed code violates an active rule." },
  { term: "Issue lifecycle", definition: "The path an issue follows from detection through review, assignment, fixing, acceptance, false-positive marking, or resolution." },
  { term: "License compliance", definition: "Checking whether dependency licenses meet an organization's legal and policy requirements." },
  { term: "Maintainability", definition: "How easy code is to understand, change, and extend. Code smells and cognitive complexity are maintainability signals." },
  { term: "MCP", definition: "Model Context Protocol, a protocol that lets AI tools connect to external systems and context providers." },
  { term: "New code", definition: "Code recently added or changed according to the project's New Code Definition." },
  { term: "New Code Definition", definition: "The configuration that decides what counts as new code, such as changes since a previous version, a number of days, or a reference branch." },
  { term: "Onboarding", definition: "The early customer phase where projects, users, integrations, and initial workflows are set up so Sonar can deliver first value." },
  { term: "Organization", definition: "An administrative grouping in SonarQube Cloud that contains projects, users, and settings." },
  { term: "Portfolio", definition: "An enterprise grouping of projects used for higher-level reporting, governance, and visibility." },
  { term: "Project", definition: "A codebase or repository configured for analysis in SonarQube Cloud or SonarQube Server." },
  { term: "Pull request", definition: "A proposed code change submitted for review before merge." },
  { term: "Pull-request analysis", definition: "Sonar analysis focused on changes introduced by a pull request, usually before merge." },
  { term: "Pull-request decoration", definition: "Showing Sonar findings and quality gate status inside the DevOps platform's pull-request interface." },
  { term: "Quality Gate", definition: "A pass/fail policy made of conditions on metrics such as issues, ratings, duplication, and code coverage." },
  { term: "Quality Gate condition", definition: "One threshold inside a Quality Gate, such as minimum coverage on new code or no new blocker issues." },
  { term: "Quality Profile", definition: "The per-language set of active rules used during analysis." },
  { term: "Reference branch", definition: "A branch used as the baseline for determining what counts as new code." },
  { term: "Reliability", definition: "The degree to which code is likely to behave correctly. Sonar bugs are reliability issues." },
  { term: "Remediation", definition: "The work of fixing an issue, reducing technical debt, or resolving a vulnerability." },
  { term: "Risk signal", definition: "Evidence that customer value or renewal health may be at risk, such as ignored quality gates or low repository adoption." },
  { term: "Rule", definition: "A coded check that detects a specific quality, reliability, maintainability, or security pattern." },
  { term: "SAST", definition: "Static Application Security Testing, which analyzes source code for security weaknesses without running the application." },
  { term: "SBOM", definition: "Software Bill of Materials, an inventory of components and dependencies included in software." },
  { term: "SCA", definition: "Software Composition Analysis, which analyzes dependencies for known vulnerabilities, license concerns, and supply-chain risk." },
  { term: "SDLC", definition: "Software Development Life Cycle, the process of planning, building, testing, reviewing, releasing, and maintaining software." },
  { term: "Secrets detection", definition: "Analysis that finds credentials, tokens, private keys, or other sensitive secrets accidentally committed to code." },
  { term: "Security Hotspot", definition: "Security-sensitive code that requires human review before deciding whether it is safe or vulnerable." },
  { term: "Security rating", definition: "A Sonar measure that summarizes security risk based on vulnerabilities and related findings." },
  { term: "Sonar way", definition: "Sonar's recommended default quality profile and quality gate, used as a practical starting standard." },
  { term: "SonarQube Cloud", definition: "Sonar's managed SaaS product for code quality and security analysis." },
  { term: "SonarQube for IDE", definition: "Sonar's IDE extension that gives developers feedback while they code." },
  { term: "SonarQube Server", definition: "Sonar's self-managed product for code quality and security analysis, deployed and operated by the customer." },
  { term: "Source and sink", definition: "In taint analysis, a source introduces untrusted data and a sink is a sensitive operation where that data can become dangerous." },
  { term: "Static analysis", definition: "Automated inspection of source code without running the application." },
  { term: "Supply-chain risk", definition: "Risk introduced through dependencies, packages, build systems, or third-party components used by software." },
  { term: "Taint analysis", definition: "A security analysis technique that tracks untrusted data as it flows from sources to dangerous sinks." },
  { term: "Technical champion", definition: "A customer stakeholder who understands the tool, advocates for adoption, and helps influence internal teams." },
  { term: "Technical debt", definition: "The future cost of fixing maintainability issues, shortcuts, or design weaknesses left in the codebase." },
  { term: "Technical success plan", definition: "A plan that connects customer goals to concrete technical actions, milestones, owners, and success metrics." },
  { term: "Time to value", definition: "How quickly a customer sees useful outcomes from Sonar, such as actionable findings, working quality gates, or improved new-code quality." },
  { term: "Usage", definition: "Activity in the product, such as analyses run or users active. Usage is helpful, but adoption means usage is embedded in workflow." },
  { term: "Value realization", definition: "Evidence that Sonar is producing outcomes the customer cares about, such as risk reduction, faster feedback, or consistent standards." },
  { term: "Verification", definition: "Independent checking that code meets quality, security, and maintainability expectations before it is trusted or released." },
  { term: "Vulnerability", definition: "A security issue that can expose software to attack or abuse." },
  { term: "Zero-trust verification", definition: "The idea that generated code, especially AI-generated code, should be independently checked rather than trusted by default." }
].sort((first, second) => first.term.localeCompare(second.term));

export function glossarySlug(term: string) {
  return term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
